apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatapp-deployment
  labels:
    app: chatapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chatapp
  template:
    metadata:
      labels:
        app: chatapp
    spec:
      containers:
      - name: chatapp
        image: 817735295857.dkr.ecr.us-east-1.amazonaws.com/repo:latest
        ports:
        - containerPort: 80
